# Notebook for Round 1 Manual Trading

## Matrix of currency exchanges

In [1]:
import numpy as np

0 - snowballs

1 - pizzas

2 - silicon nuggets

3 - seashells (our own currency)


We can to up to 5 trades, starting and ending with seashells.

Row index = currency we have

col index = currency we convert into

In [64]:
A = np.array([
    [1, 1.45, 0.52, 0.72],
    [0.7, 1, 0.31, 0.48],
    [1.95, 3.1, 1, 1.49],
    [1.34, 1.98, 0.68, 1]
])
A

array([[1.  , 1.45, 0.52, 0.72],
       [0.7 , 1.  , 0.31, 0.48],
       [1.95, 3.1 , 1.  , 1.49],
       [1.34, 1.98, 0.68, 1.  ]])

Dynamical programming approach 

solve general problem - for any two products (x, y) and n trades find the highest total exchange rate starting at x and ending at y using n trades (trade path of length n+1).

In [58]:
# initialize matrix of optimal trade rates
A_cur = A

# matrix to keep of optimal trade sequence
B_cur = [['']*4 for _ in range(4)]
# B_cur = np.array(B_cur)
for i in range(4):
    for j in range(4):
        B_cur[i][j] = str(i) + str(j)

In [59]:
print(A_cur, B_cur)

[[1.   1.45 0.52 0.72]
 [0.7  1.   0.31 0.48]
 [1.95 3.1  1.   1.49]
 [1.34 1.98 0.68 1.  ]] [['00', '01', '02', '03'], ['10', '11', '12', '13'], ['20', '21', '22', '23'], ['30', '31', '32', '33']]


In [60]:
for n in range(3, 6):
    print(f'n: {n}')
    print(f'A_cur: {A_cur}')
    print(f'B_cur: {B_cur} \n')
    A_prev = A_cur.copy()
    B_prev = B_cur.copy()
    B_cur = [['']*4 for _ in range(4)]
    #B_cur = np.array([['']*4 for _ in range(4)])
    for i in range(4):
        for k in range(4):
            max_rate = 0
            for j in range(4):
                rate_ij = A_prev[i][j]
                rate_jk = A[j][k]
                rate_tot = rate_ij * rate_jk
                if rate_tot > max_rate:
                    max_rate = rate_tot
                    optimal_path = B_prev[i][j] + str(k)
                A_cur[i][k] = max_rate
                B_cur[i][k] = optimal_path
        

n: 3
A_cur: [[1.   1.45 0.52 0.72]
 [0.7  1.   0.31 0.48]
 [1.95 3.1  1.   1.49]
 [1.34 1.98 0.68 1.  ]]
B_cur: [['00', '01', '02', '03'], ['10', '11', '12', '13'], ['20', '21', '22', '23'], ['30', '31', '32', '33']] 

n: 4
A_cur: [[1.015      1.612      0.52       0.7748    ]
 [0.7105     1.1284     0.364      0.54236   ]
 [2.20255    3.49804    1.1284     1.681316  ]
 [1.497734   2.3786672  0.767312   1.14329488]]
B_cur: [['010', '021', '002', '023'], ['100', '101', '102', '103'], ['210', '211', '212', '213'], ['320', '321', '322', '323']] 

n: 5
A_cur: [[1.1604443  1.84299135 0.59451334 0.88582487]
 [0.93036092 1.47757813 0.47663811 0.71019078]
 [3.67230978 5.83227918 1.88138038 2.80325677]
 [3.22158473 5.11644787 1.65046705 2.45919591]]
B_cur: [['0230', '0231', '0232', '0233'], ['1010', '1011', '1012', '1013'], ['2120', '2121', '2122', '2123'], ['3230', '3231', '3232', '3233']] 



In [53]:
B_cur

[['00000', '00001', '00002', '00003'],
 ['10000', '10001', '10002', '10003'],
 ['20000', '20001', '20002', '20003'],
 ['30000', '30001', '30002', '30003']]

In [49]:
A_cur

array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [65]:
max_rate = -1
for i1 in range(4):
    for i2 in range(4):
        for i3 in range(4):
            for i4 in range(4):
                rate_tot = A[3][i1] * A[i1][i2] * A[i2][i3] * A[i3][i4] * A[i4][3]
                if rate_tot > max_rate:
                    max_rate = rate_tot
                    optimal_path = '3' + str(i1) + str(i2) + str(i3) + str(i4) + '3'

In [66]:
max_rate

1.14329488

In [67]:
optimal_path

'321023'